/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EllipsedText {
    'test': String;
    'update': () => Promise<void>;
  }
}

declare global {


  interface HTMLEllipsedTextElement extends Components.EllipsedText, HTMLStencilElement {}
  var HTMLEllipsedTextElement: {
    prototype: HTMLEllipsedTextElement;
    new (): HTMLEllipsedTextElement;
  };
  interface HTMLElementTagNameMap {
    'ellipsed-text': HTMLEllipsedTextElement;
  }
}

declare namespace LocalJSX {
  interface EllipsedText extends JSXBase.HTMLAttributes<HTMLEllipsedTextElement> {
    'test'?: String;
  }

  interface IntrinsicElements {
    'ellipsed-text': EllipsedText;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


